module.exports = {
  whiteCards: [
    "Scaccolarsi con l'alluce del piede sinistro.",
    "Avere peli pubici fra i denti.",
    "Bomba Atomica.",
    "The Big Bang Theory.",
    "Pulire un water incrostato, in un autogrill nel napoletano.",
    "Tatuaggio sbagliato.",
    "Martello Pneumatico.",
    "Cavallo Pazzo.",
    "Cicciolina nuda.",
    "Sheldon Cooper.",
    "BAZINGA!!",
    "Si trasforma in un razzo missile.",
    "Uscimmo a riveder le stelle.",
    "Giovanni Verga.",
    "Poliziotti senza pantaloni con grossi problemi di igiene personale.",
    "Un'orda famelica di napoletani che non hanno pagato il grattino e vogliono il pizzo!",
    "Aver paura dei vicoli bui mentre cammini per strada con addosso soltanto un impermeabile rosa.",
    "Tarapia tapioco come se fosse antani con la supercazzola prematurata, con lo scappellamento a destra.",
    "Un panino col prosciutto.",
    "Organizzare cene eleganti per scopi professionali.",
    "Simulare un orgasmo gridando come una capra affamata.",
    "Una Peroni sudata.",
    "La nipote di Mubarack.",
    "Un vaffanculo a colazione è quello che ci vuole.",
    "Ho stato io.",
    "Il celodurismo bossiano.",
    "Scorreggiare nell'ascensore affollato e guardare schifato quello accanto. ",
    "Volere la botte piena, la moglie ubriaca e un cazzo in culo.",
    "Un milione per gli organizzatori, dieci per la questura.",
    "Dormire a quattro di spade come non ci fosse un domani.",
    "Cose che voi umani non potete nemmeno immaginare.",
    "Mangiare il ben di Dio e cagare l'opera del diavolo.",
    "Diabolico nell'amplesso, sproporzionato per quel che riguarda le dimensioni del sesso.",
    "Il generatore di fusione che dà energia ai tempo-circuiti e al flusso canalizzatore.",
    "Schiacciare i ricci con il culo.",
    "Ascoltare Marco Masini durante un giro alla Roulette Russa.",
    "Travestirsi da puttanone da competizione.",
    "Pierluca Scaccolarsi al semaforo e dire al venditore che non voglio i fazzoletti.",
    "Fare i gargarismi con il cemento liquido a presa rapida.",
    "Controllare le sgommate nelle mutande.",
    "Fare una puzza ed incolpare il cane.",
    "Dire,appena svegli, \"buongiorno Aaamore\" aspirando la A per 3 sec.",
    "Autopsicanalisi.",
    "La crisi economica.",
    "L'ascella maleodorante.",
    "Vendere la verginità su ebay.",
    "Truccarsi come Moira Orfei.",
    "Guidare a fari spenti nella notte per vedere, se poi è tanto difficile morire.",
    "Perché tutto attaccato si scrive staccato mentre staccato si scrive tutto attaccato?",
    "Essere inculato con veemenza, senza vasellina e con la sabbia da un nero mastodontico.",
    "William Wallace in una spiaggia di nudisti",
    "Obi Wan Kenobi che simula una pugnetta con la spada laser",
    "La mamma di Stifler",
    "Fare economia comprando la carta igienica ruvida",
    "Salto della quaglia",
    "Video porno di Belen",
    "Mutande piene di sabbia [della lettiera del gatto]",
    "Peli pubici di sconosciuti",
    "Saponette fatte con grasso umano",
    "Pianta di ficus, simbolo del potere",
    "Cotton fioc usati",
    "L'occhio di Sauron con la congiuntivite",
    "Un caffè corretto con del pessimo piscio di cane",
    "Riaccendersi il mozzicone di una sigaretta trovata per terra",
    "L'insistente signorina che ti propone di cambiare piano telefonico",
    "Scorreggiare così tanto da far scattare l'allarme antigas.",
    "Scaccolarsi il naso ed essere scoperti.",
    "Cristiano Malgioglio.",
    "Toccarsi i genitali senza farsi vedere.",
    "Sculacciata.",
    "Uomini nudi che fanno l'elicottero.",
    "Marshmallows avvelenati.",
    "Il 69.",
    "La versione porno dei Simpsons.",
    "Squali volanti.",
    "Fare piedino alla persona sbagliata.",
    "Fare un rutto mentre si recita la poesia di Natale.",
    "Suocera rompipalle.",
    "Sbagliare DVD e far partire un porno.",
    "Vecchietti che guardano lavori in corso con le braccia dietro la schiena.",
    "Una collezione di porno con protagonisti nani ben dotati.",
    "Blue screen of death",
    "La pipì che scappa appena usciti di casa",
    "Un cane che lecca il gelato spalmato sulle tue palle.",
    "Il funerale di Nietzsche.",
    "Un quadro dipinto da una scimmia con le emorroidi.",
    "Annusare il culo ai passanti credendosi un cane.",
    "Pulizia Etnica.",
    "WikiLeaks.",
    "Essere controllati dagli USA tramite l'NSA.",
    "Agenti FBI che si comportano come checche isteriche.",
    "Mettere il dito nel culo di pikachu e prendere la scossa.",
    "Fingere un malessere per non rispondere ad una domanda",
    "Diventare invisibile e fare scherzi sconci alle ragazze negli spogliatoi delle piscine comunali, mentre il vescovo è in visita alla struttura.",
    "Bambole voodoo.",
    "Acconciarsi i capelli con letame di cavallo.",
    "Sfidarsi a una gara di lancio di bocce incendiarie.",
    "Un nuovo sistema di allungamento del pene.",
    "Farsi un piercing ai genitali con una sparachiodi.",
    "Porno acrobatico.",
    "Un rutto da Coppa dei Campioni.",
    "Gare di rutti.",
    "Apparire come guest star nel nuovo video di Gemmadelsud.",
    "Infilarsi un ravanello nel culo.",
    "Mangiare teste umane.",
    "Tingersi il pube a righe bianche e rosa.",
    "Brucare.",
    "Autoerotismo.",
    "Action Man.",
    "Entrare in una chiesa urlando di essere l'Anticristo.",
    "Pollo di gomma con carrucola.",
    "Uno svizzero, un francese, un tedesco e un'italiano.",
    "L'uomo saggio ama usare l'ombrello quando piove!",
    "L'uomo coraggioso ama sentire la natura sulla pelle.",
    "Ho visto cose che voi umani non potreste immaginare...",
    "BitTorrent",
    "Riso Patate e Cozze.",
    "Voglio Godere!!!",
    "Un mondo di dolore!",
    "Finchè c'è vita c'è speranza.",
    "Ferrari FF",
    "Qui e lì, notte e dì, questo il mondo fa girar.",
    "Fiamme torreggianti.",
    "Sono il conducente del treno di cacca!",
    "A Kuala Lumpur nel quartiere dei ladyboy.",
    "Navi da combattimento in fiamme al largo dei bastioni di Orione e raggi B balenare nel buio vicino alle porte di Tannhauser.",
    "Un Tandem.",
    "La pillola del giorno dopo.",
    "Al mio via scatenate l'inferno!",
    "Drag queen.",
    "Acido Acetilsalicilico.",
    "Il gatto di Schrodinger.",
    "La Sirenetta di Copenaghen.",
    "Un Clochard.",
    "Vita morte e miracoli.",
    "Supercalifragili- stichespiralidoso.",
    "Il Jolly Roger.",
    "Uno alla testa ed uno al cuore.",
    "Il K2.",
    "Bevo il the a testa in giù usando i piedi.",
    "L'aiuto del pubblico.",
    "Matitina IKEA.",
    "Dieta mediterranea.",
    "Tre Metri Sopra il Cielo.",
    "Jessica Fletcher.",
    "Fughe di gas.",
    "Evadere il canone RAI.",
    "Alice nel Paese delle Pornomeraviglie.",
    "Un tristissimo film Bielorusso.",
    "Adolescenti arrapati.",
    "Bombardamenti indiscriminati.",
    "L'ennesima canzone neomelodica napoletana.",
    "Reggere la candela.",
    "Mirabolanti cadute da tacco 12!",
    "Il Colonnello Giuliacci.",
    "Milf estremamente espansive!",
    "Sindrome di Down",
    "PornoStar con desideri sessuali per il proprio padre",
    "Comprare due banane per mangiarne almeno una",
    "Immigrati clandestini",
    "Cowboy gay che mangiano budino",
    "Ascelle puzzolenti",
    "Un ninja con una diarrea incontrollabile",
    "Un culo grasso in pantaloni da yoga",
    "Usare poco lubrificante",
    "Un seno così floscio che le arriva alle ginocchia",
    "Un travestito",
    "Cercatore d'oro",
    "Scrivere un sms alla propria EX mentre si è ubriachi di vodka",
    "Una Death Race tra sedie a rotelle",
    "Un aborto fallito.",
    "Realizzare che è finita la carta igenica quando ormai è troppo tardi",
    "Una tanadi tigri del bengala affamate.",
    "Macchie non identificabili sulla punta del pene.",
    "Capelli nello scarico della doccia.",
    "Botulino.",
    "Anoressia.",
    "Lupus.",
    "Doctor House.",
    "Schiavitù.",
    "Spada Laser.",
    "Feci spalmate sulla parete del bagno.",
    "Pirati inesperti.",
    "Allergia ai Preservativi.",
    "Guardare un porno in pubblico sull'iPad a tutto volume.",
    "Facebook.",
    "Una pellicola in Super-8 della prima GangBang della nonna.",
    "M2O",
    "Test della gravidanza.",
    "GloryHole.",
    "Kim Jong Un.",
    "Anime Hentai.",
    "Penny!? Penny!? Penny!?",
    "Un negro di origine asiatica.",
    "Dolore da emorroidi.",
    "Necromanzia.",
    "Massaggiatrici cinesi molto esperte.",
    "Traffico d'organi.",
    "Lavoro sottopagato.",
    "Riportare in vita i morti.",
    "Vendere organi umani a basso costo e con scarse garanzie igeniche.",
    "Epatite C contratta mangiando cozze crude.",
    "Lenti a contatto a raggi X.",
    "Ridere a crepapelle per nascondere una sonora puzza.",
    "Palpatina furtiva.",
    "Orsi polari che ballano il dadaumpa.",
    "Un pappagallo che dice cose sconce.",
    "Isabella.",
    "Animali domestici guardoni.",
    "Gattini ninja.",
    "Crisi di mezza età.",
    "Un superdotato.",
    "L'uomo tigre.",
    "Un palestrato con micropene.",
    "Primo bacio con l'alito di aglio.",
    "Uno spinello.",
    "Bicicletta senza sellino.",
    "Pensare di stare per saltare su un bel tronco e finire in una merda di vacca.",
    "Un hippie che si è appena fatto di LSD.",
    "Scroto.",
    "Vomitare a denti stretti per sentire i pezzettoni.",
    "Avere peli pubici fra i denti."
  ],
  blackCards: [
    { text: "Arricchisciti rapidamente con _", pick: 1 },
    { text: "_ è la radice di tutti i mali del mondo!", pick: 1 },
    { text: "Mors tua, vita mea. _ tua, vita _", pick: 2 },
    { text: "Il video della canzone \"YMCA\" fu registrato dai VillagePepole vestiti  da marinaio, pompiere, indiano e _", pick: 1 },
    { text: "Era una notte buia e tempestosa. Ad un tratto la porta sbattè e _", pick: 1 },
    { text: "KEEP CALM AND _", pick: 1 },
    { text: "L'Italia è fallita! Non ci sono più soldi. Adesso non mi resta che _", pick: 1 },
    { text: "Benvenuti nella terra di _ dove potrete ammirare _ allo stato brado!", pick: 2 },
    { text: "Salendo in soffitta ho aperto l'antico baule di mia nonna e al suo interno ho trovato _", pick: 1 },
    { text: "E' il mio primo volo in aereo, ma il passeggero seduto accanto a me _", pick: 1 },
    { text: "Ciao, sono Silvio Berlusconi e quando verrò eletto restituirò _", pick: 1 },
    { text: "Ogni volta che ascolto in tv la voce di _ mi vien voglia di _", pick: 2 },
    { text: "Caro Babbo Natale, quest'anno in regalo vorrei _", pick: 1 },
    { text: "Amore mio, sono qui in ginocchio davanti a te per _", pick: 1 },
    { text: "A proposito di _, per me la soluzione è _", pick: 2 },
    { text: "Non so _, ora cerco come si fa su youtube!", pick: 1 },
    { text: "Il mio primo pensiero al mattino è _", pick: 1 },
    { text: "Piuttosto che andare dalla suocera, preferisco _", pick: 1 },
    { text: "Oggi ti vedo strano, non ti senti bene? Non è che hai mangiato _", pick: 1 },
    { text: "L'altra sera mentre portavo a spasso il cane, ho visto _ che con aria sospetta stava per _", pick: 2 },
    { text: "Oggi _ mi sembra davvero molto _", pick: 2 },
    { text: "A _ quando è in bagno, piace pensare a _", pick: 2 },
    { text: "Prova il nuovo philadelphia al gusto di _", pick: 1 },
    { text: "Quando aprì il vaso, Pandora vi trovò un'unica cosa: _", pick: 1 },
    { text: "Dlin dlon, un addetto pulizie al reparto _", pick: 1 },
    { text: "Il peggior regalo di natale mai avuto da bambino è stato _", pick: 1 },
    { text: "Rocco Siffredi nel tempo libero colleziona _", pick: 1 },
    { text: "\"Mamma/papà come nascono i bambini?\" Come gli rispondi? _", pick: 1 },
    { text: "Walt Disney presenta _ un nuovo cartoon che parla di _", pick: 2 },
    { text: "Stai facendo sesso selvaggio e succede che _", pick: 1 },
    { text: "Il 1930 è spesso indicato come l'età d'oro del _", pick: 1 },
    { text: "La verità è che alla fine dell'universo c'è soltanto _", pick: 1 },
    { text: "E' ampiamente diffusa l'idea che i nostri antenati non si sarebbero mai evoluti senza _", pick: 1 },
    { text: "Un_ al giorno leva _ di torno!", pick: 2 },
    { text: "Ho un'idea vincente per un nuovo programma tv. _", pick: 1 },
    { text: "La ricetta del successo. _", pick: 1 },
    { text: "Qual è la nuova dieta del momento? _", pick: 1 },
    { text: "Un'invenzione che potrebbe salvare il mondo. _", pick: 1 },
    { text: "Vieni sorpreso da un temporale, per non bagnarti ti rifugi _", pick: 1 },
    { text: "Uccidi i tuoi nemici con _", pick: 1 },
    { text: "Al primo appuntamento ti presenti con? _", pick: 1 },
    { text: "Primo classificato: _", pick: 1 },
    { text: "La mia ultima frase sul letto di morte sarebbe: _", pick: 1 },
    { text: "_ non così che vi fate male!", pick: 1 },
    { text: "Vorrei _ per conquistare _", pick: 2 },
    { text: "C'è crisi, si torna al baratto: _ per _.", pick: 2 },
    { text: "Avevo un piano perfetto, ma non avevo considerato _.", pick: 1 },
    { text: "_. Così è la vita!", pick: 1 },
    { text: "Il mio sogno ricorrente: _ che _.", pick: 2 },
    { text: "Quale sarà la nostra ultima speranza quando un nuovo Demone-Robot invaderà il mondo?", pick: 1 },
    { text: "Quando ho visto tua madre nuda, mi ha ricordato _", pick: 1 },
    { text: "Hanno appena trovato un _ nei rifiuti dell'ospedale di Napoli.", pick: 1 },
    { text: "Adoro l'odore di _ la mattina.", pick: 1 },
    { text: "In realtà l'11 settembre fu organizzato da _", pick: 1 },
    { text: "Il Sacro Graal descritto nella Bibbia in realtà non è un calice ma è _", pick: 1 },
    { text: "La felicità è _", pick: 1 },
    { text: "Che ore sono? E' l'ora di_!", pick: 1 },
    { text: "La nonna mi diceva sempre che _, mi avrebbe reso cieco!", pick: 1 },
    { text: "_ è l'ottavo peccato capitale!", pick: 1 },
    { text: "Il dottore mi ha comunicato con faccia severa che il mio era un grave caso di _", pick: 1 },
    { text: "Mi prodigherei in un ricco pompino soltanto per _", pick: 1 },
    { text: "Baci il rospo ma, invece di trasformarsi in un principe, diventa _", pick: 1 },
    { text: "La più grande disavventura che può capitare a una donna è _", pick: 1 },
    { text: "\"Mamma mamma perchè papà indossa le scarpe col tacco 12?\"", pick: 1 },
    { text: "Obama ha un tatuaggio nascosto che raffigura _", pick: 1 },
    { text: "Cos'hai fatto l'estate scorsa?", pick: 1 },
    { text: "Sei simpatico come _", pick: 1 },
    { text: "Questa bibita energetica ha un sapore di _", pick: 1 },
    { text: "L'assenza di _ è un evidente sintomo di _", pick: 2 },
    { text: "Rimedi naturali per combattere l'aerofagia: _", pick: 1 },
    { text: "Dopo 10 anni di fidanzamento ti lascia con due semplici parole: <i>\"sono omosessuale\"</i>. La tua reazione è _", pick: 1 },
  ],
  name: "Pack Pasta e Pizza"

};